# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_function_A <- function(x) {
    .Call(`_t4stats_my_function_A`, x)
}

my_function_B <- function(x) {
    .Call(`_t4stats_my_function_B`, x)
}

